name: Build Website

on:
  push:
    branches: [rspress]
    paths:
      - 'docs/**'

  schedule:
    - cron: '15 0 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: rspress
          fetch-depth: 0
      - name: Install Pnpm
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Nx Cache
        id: nx-cache
        uses: actions/cache@v3
        with:
          path: .nx-cache
          key: nx-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            nx-${{ github.ref_name }}-
            nx-

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Main Doc
        run: pnpm build

      # - name: Deploy to vercel 🚀
      #   uses: amondnet/vercel-action@v20
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     github-token: ${{ secrets.ACCESS_TOKEN  }}
      #     vercel-args: '--prod' #Optional
      #     vercel-org-id: ${{ secrets.ORG_ID}}
      #     vercel-project-id: ${{ secrets.RSPRESSID }}
      #     working-directory: ./doc_build/
