name: claer
on:
  schedule:
    - cron: '0 15 * * 4' # Runs at 15:00 UTC on Thu.
  workflow_dispatch:
env:
  TZ: Asia/Shanghai

jobs:
  clear:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚀
        uses: actions/checkout@v2
        with:
          repository: 'jdsync/Workflows-Cleaner'
          fetch-depth: 0
      - name: Set up Python 🚀
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Clear 🚀
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EXPIRE_TIME: '1h'
        run: |
          python -m pip install --upgrade pipenv wheel
          pipenv install
          pipenv run python run.py
